'use client';

import { useState, useEffect } from 'react';

const sections = [
  { id: 'acceptance', title: 'Acceptance of Terms' },
  { id: 'definitions', title: 'Definitions' },
  { id: 'account', title: 'Your Account' },
  { id: 'acceptable-use', title: 'Acceptable Use' },
  { id: 'data-ownership', title: 'Data Ownership' },
  { id: 'intellectual-property', title: 'Intellectual Property' },
  { id: 'payment-billing', title: 'Payment & Billing' },
  { id: 'service-availability', title: 'Service Availability' },
  { id: 'ai-features', title: 'AI Features' },
  { id: 'third-party', title: 'Third-Party Services' },
  { id: 'limitation', title: 'Limitation of Liability' },
  { id: 'indemnification', title: 'Indemnification' },
  { id: 'termination', title: 'Termination' },
  { id: 'changes', title: 'Changes to Terms' },
  { id: 'governing-law', title: 'Governing Law' },
  { id: 'contact', title: 'Contact' },
];

export default function TermsContent() {
  const [activeSection, setActiveSection] = useState('acceptance');

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        }
      },
      { rootMargin: '-20% 0px -60% 0px' }
    );

    sections.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <div className="py-16 md:py-24 px-4 sm:px-6 md:px-8 bg-white">
      <div className="mx-auto max-w-6xl">
        {/* Header */}
        <div className="mb-12 md:mb-16">
          <p className="text-xs font-medium tracking-widest uppercase text-blue-600 mb-3">Legal</p>
          <h1 className="text-3xl md:text-5xl font-normal text-black mb-3">Terms of Service</h1>
          <p className="text-base text-neutral-500">Last updated: June 2, 2026</p>
        </div>

        {/* Layout: sidebar + content */}
        <div className="flex gap-16">
          {/* Sticky sidebar - desktop only */}
          <nav className="hidden lg:block w-56 shrink-0">
            <div className="sticky top-24 space-y-1">
              {sections.map(({ id, title }) => (
                <a
                  key={id}
                  href={`#${id}`}
                  className={`block text-[13px] py-1.5 pl-3 border-l-2 transition-colors ${
                    activeSection === id
                      ? 'border-black text-black font-medium'
                      : 'border-transparent text-neutral-400 hover:text-neutral-700'
                  }`}
                >
                  {title}
                </a>
              ))}
            </div>
          </nav>

          {/* Main content */}
          <div className="flex-1 min-w-0 max-w-3xl">

            {/* Section 1 */}
            <section id="acceptance" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">1. Acceptance of Terms</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                By creating an account, accessing, or using Luxe AI (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, you may not use the Service.
              </p>
              <div className="bg-amber-50 border border-amber-100 rounded-lg p-4">
                <p className="text-[15px] text-neutral-700">
                  <strong>These Terms form a legally binding agreement</strong> between you and Kintari Technologies Limited. Please read them carefully before using our platform.
                </p>
              </div>
            </section>

            {/* Section 2 */}
            <section id="definitions" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">2. Definitions</h2>
              <div className="space-y-2">
                {[
                  { term: '"Service"', def: 'The Luxe AI platform including the web application (luxeai.anasatech.com), customer app (customer.anasatech.com), APIs, and all related services.' },
                  { term: '"Account Owner"', def: 'The individual or business entity that registers for and manages a Luxe AI account.' },
                  { term: '"Authorized User"', def: 'Any individual granted access to the Service by an Account Owner (e.g., employees).' },
                  { term: '"Customer Data"', def: 'All data uploaded, entered, or generated by you through the Service, including business records, transactions, and customer information.' },
                  { term: '"We", "Us", "Our"', def: 'Kintari Technologies Limited, trading as Anasatech.' },
                  { term: '"You", "Your"', def: 'The Account Owner or Authorized User accessing the Service.' },
                ].map((item, i) => (
                  <div key={i} className="flex items-start gap-3 py-2.5 border-b border-neutral-100 last:border-0">
                    <span className="text-[15px] font-semibold text-black w-40 shrink-0">{item.term}</span>
                    <span className="text-[15px] text-neutral-600">{item.def}</span>
                  </div>
                ))}
              </div>
            </section>

            {/* Section 3 */}
            <section id="account" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">3. Your Account</h2>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">Registration</h3>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-4">
                You must provide accurate, complete information when creating an account. Account Owners must be at least <strong>18 years old</strong>. Authorized Users must be at least <strong>16 years old</strong>.
              </p>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">Account Security</h3>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">You are responsible for:</p>
              <ul className="space-y-1.5 mb-4 ml-4">
                <li className="text-[15px] text-neutral-600">• Maintaining the confidentiality of your login credentials</li>
                <li className="text-[15px] text-neutral-600">• All activities that occur under your account</li>
                <li className="text-[15px] text-neutral-600">• Notifying us immediately of any unauthorized access</li>
              </ul>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">Multi-User Accounts</h3>
              <p className="text-[15px] text-neutral-700 leading-relaxed">
                Account Owners are responsible for the actions of all Authorized Users they add to their account. This includes employee access, role permissions, and any data those users create or modify.
              </p>
            </section>

            {/* Section 4 */}
            <section id="acceptable-use" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">4. Acceptable Use</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-4">
                You agree <strong>not</strong> to use the Service to:
              </p>
              <div className="space-y-2">
                {[
                  'Engage in fraudulent transactions, money laundering, or illegal activity',
                  'Process payments for prohibited goods or services',
                  'Attempt to access other users\' accounts or data',
                  'Reverse-engineer, decompile, or attempt to extract source code',
                  'Use automated scripts or bots to access the Service',
                  'Transmit viruses, malware, or other harmful code',
                  'Resell or sublicense access to the Service without our written consent',
                  'Misuse the AI features to generate harmful, illegal, or misleading content',
                ].map((item, i) => (
                  <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-red-50/50 border border-red-100/50">
                    <svg className="w-4 h-4 text-red-500 shrink-0 mt-0.5" fill="none" stroke="currentColor" strokeWidth={2.5} viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                    <span className="text-[14px] text-neutral-700">{item}</span>
                  </div>
                ))}
              </div>
              <p className="text-[15px] text-neutral-700 leading-relaxed mt-4">
                Violation of these terms may result in immediate suspension or termination of your account.
              </p>
            </section>

            {/* Section 5 */}
            <section id="data-ownership" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">5. Data Ownership</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
                <div className="p-4 rounded-lg bg-green-50 border border-green-100">
                  <p className="text-base font-semibold text-black mb-1">Your Data = Yours</p>
                  <p className="text-sm text-neutral-600">All Customer Data you upload or generate through the Service belongs to you. We do not claim ownership of your business data.</p>
                </div>
                <div className="p-4 rounded-lg bg-blue-50 border border-blue-100">
                  <p className="text-base font-semibold text-black mb-1">Our Platform = Ours</p>
                  <p className="text-sm text-neutral-600">The Service itself — code, design, algorithms, and infrastructure — is owned by Kintari Technologies Limited.</p>
                </div>
              </div>
              <p className="text-[15px] text-neutral-700 leading-relaxed">
                You grant us a limited license to use your Customer Data solely for the purpose of providing and improving the Service. This license terminates when you delete your account.
              </p>
            </section>

            {/* Section 6 */}
            <section id="intellectual-property" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">6. Intellectual Property</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                The Service, including all software, designs, trademarks (Luxe AI, Anasatech), documentation, and content created by us, is protected by intellectual property laws. You may not:
              </p>
              <ul className="space-y-1.5 ml-4">
                <li className="text-[15px] text-neutral-600">• Copy, modify, or distribute any part of the Service</li>
                <li className="text-[15px] text-neutral-600">• Use our trademarks without written permission</li>
                <li className="text-[15px] text-neutral-600">• Create derivative works based on the Service</li>
                <li className="text-[15px] text-neutral-600">• Remove any proprietary notices or labels</li>
              </ul>
            </section>

            {/* Section 7 */}
            <section id="payment-billing" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">7. Payment & Billing</h2>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">Subscription Plans</h3>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                The Service is offered under two billing models:
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
                <div className="p-4 rounded-lg bg-neutral-50 border border-neutral-100">
                  <p className="text-base font-semibold text-black mb-1">Fixed Subscription</p>
                  <p className="text-sm text-neutral-600">A flat fee billed in advance on a monthly or annual cycle. Prices are displayed in the applicable local currency at signup.</p>
                </div>
                <div className="p-4 rounded-lg bg-neutral-50 border border-neutral-100">
                  <p className="text-base font-semibold text-black mb-1">Revenue-Based Plan</p>
                  <p className="text-sm text-neutral-600">A fee of 0.8% of your recorded sales revenue, calculated and charged on a weekly or monthly basis. No upfront payment required.</p>
                </div>
              </div>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">Payment Methods</h3>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-4">
                Payments are processed through Paystack. We accept Mobile Money (MTN, Telecel, AirtelTigo), Visa, Mastercard, and other methods supported by our payment processor.
              </p>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">No Refunds</h3>
              <div className="bg-amber-50 border border-amber-100 rounded-lg p-4 mb-4">
                <p className="text-[15px] text-neutral-700">
                  <strong>All payments are non-refundable.</strong> For fixed subscriptions, once a payment is made it cannot be reversed, refunded, or credited — including partial months or unused periods. For revenue-based plans, fees charged based on recorded sales are final. You may cancel your subscription at any time, and access will continue until the end of the current billing period.
                </p>
              </div>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">Pricing Changes</h3>
              <p className="text-[15px] text-neutral-700 leading-relaxed">
                We may change subscription pricing with <strong>at least 30 days&apos; written notice</strong>. Continued use after the price change takes effect constitutes acceptance. You may cancel before the new pricing applies.
              </p>
            </section>

            {/* Section 8 */}
            <section id="service-availability" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">8. Service Availability</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                We use commercially reasonable efforts to maintain the availability of the Service. However:
              </p>
              <ul className="space-y-1.5 ml-4 mb-4">
                <li className="text-[15px] text-neutral-600">• We do not guarantee uninterrupted or error-free operation</li>
                <li className="text-[15px] text-neutral-600">• Scheduled maintenance may temporarily limit access (we will provide advance notice where possible)</li>
                <li className="text-[15px] text-neutral-600">• Force majeure events (natural disasters, infrastructure failures, government actions) may affect availability</li>
              </ul>
              <p className="text-[15px] text-neutral-700 leading-relaxed">
                We are not liable for any losses resulting from downtime or service interruptions.
              </p>
            </section>

            {/* Section 9 */}
            <section id="ai-features" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">9. AI Features</h2>
              <div className="bg-blue-50 border border-blue-100 rounded-lg p-4 mb-4">
                <p className="text-[15px] text-neutral-700">
                  <strong>AI-generated insights are assistive in nature.</strong> They are not professional financial, legal, or business advice. You should exercise independent judgment when making business decisions.
                </p>
              </div>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                By using the AI features, you acknowledge that:
              </p>
              <ul className="space-y-1.5 ml-4">
                <li className="text-[15px] text-neutral-600">• AI responses may occasionally be inaccurate or incomplete</li>
                <li className="text-[15px] text-neutral-600">• AI features rely on the data you provide — the quality of insights depends on data accuracy</li>
                <li className="text-[15px] text-neutral-600">• We may use anonymized interaction patterns to improve AI quality (never your raw business data)</li>
                <li className="text-[15px] text-neutral-600">• AI features may evolve, change, or be discontinued with notice</li>
              </ul>
            </section>

            {/* Section 10 */}
            <section id="third-party" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">10. Third-Party Services</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                The Service integrates with third-party providers (payment processors, AI model providers, cloud hosting). These services are governed by their own terms and privacy policies. We are not responsible for:
              </p>
              <ul className="space-y-1.5 ml-4">
                <li className="text-[15px] text-neutral-600">• Outages or failures of third-party services</li>
                <li className="text-[15px] text-neutral-600">• Changes to third-party terms or pricing</li>
                <li className="text-[15px] text-neutral-600">• Data handling by third-party services beyond our control</li>
              </ul>
            </section>

            {/* Section 11 */}
            <section id="limitation" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">11. Limitation of Liability</h2>
              <div className="bg-neutral-50 border border-neutral-200 rounded-lg p-5">
                <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                  <strong>To the maximum extent permitted by law:</strong>
                </p>
                <ul className="space-y-2 ml-4">
                  <li className="text-[15px] text-neutral-600">• The Service is provided <strong>&ldquo;as is&rdquo;</strong> and <strong>&ldquo;as available&rdquo;</strong> without warranties of any kind</li>
                  <li className="text-[15px] text-neutral-600">• We shall not be liable for any <strong>indirect, incidental, special, consequential, or punitive damages</strong></li>
                  <li className="text-[15px] text-neutral-600">• This includes lost profits, lost data, business interruption, or any losses arising from use or inability to use the Service</li>
                  <li className="text-[15px] text-neutral-600">• Our total aggregate liability shall not exceed the amount you paid us in the <strong>12 months preceding the claim</strong></li>
                </ul>
              </div>
            </section>

            {/* Section 12 */}
            <section id="indemnification" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">12. Indemnification</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed">
                You agree to indemnify and hold harmless Kintari Technologies Limited, its officers, directors, and employees from any claims, damages, or expenses arising from:
              </p>
              <ul className="space-y-1.5 ml-4 mt-3">
                <li className="text-[15px] text-neutral-600">• Your use of the Service</li>
                <li className="text-[15px] text-neutral-600">• Violation of these Terms</li>
                <li className="text-[15px] text-neutral-600">• Infringement of any third-party rights</li>
                <li className="text-[15px] text-neutral-600">• Actions of your Authorized Users</li>
                <li className="text-[15px] text-neutral-600">• Data you collect from your customers through the platform</li>
              </ul>
            </section>

            {/* Section 13 */}
            <section id="termination" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">13. Termination</h2>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">By You</h3>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-4">
                You may cancel your subscription and close your account at any time. Access continues until the end of the current billing period. After account closure, your data will be deleted in accordance with our <a href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</a> (within 90 days).
              </p>

              <h3 className="text-base font-semibold text-black mt-6 mb-2">By Us</h3>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                We may suspend or terminate your account if you:
              </p>
              <ul className="space-y-1.5 ml-4 mb-4">
                <li className="text-[15px] text-neutral-600">• Violate these Terms or the Acceptable Use policy</li>
                <li className="text-[15px] text-neutral-600">• Fail to pay subscription fees after notice</li>
                <li className="text-[15px] text-neutral-600">• Engage in activity that harms other users or the Service</li>
                <li className="text-[15px] text-neutral-600">• Are required by law enforcement or court order</li>
              </ul>
              <p className="text-[15px] text-neutral-700 leading-relaxed">
                Where possible, we will provide notice and an opportunity to cure violations before termination.
              </p>
            </section>

            {/* Section 14 */}
            <section id="changes" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">14. Changes to These Terms</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed">
                We may update these Terms from time to time. When we make material changes, we will notify you via email or in-app notification <strong>at least 14 days before</strong> changes take effect. Continued use after the effective date constitutes acceptance. If you do not agree with updated Terms, you must stop using the Service and close your account.
              </p>
            </section>

            {/* Section 15 */}
            <section id="governing-law" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">15. Governing Law & Disputes</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-3">
                These Terms are governed by the laws of the <strong>Republic of Ghana</strong>. Any disputes arising from or relating to these Terms or the Service shall be submitted to the exclusive jurisdiction of the <strong>courts of Ghana</strong>.
              </p>
              <p className="text-[15px] text-neutral-700 leading-relaxed">
                Before filing any formal dispute, you agree to attempt to resolve the matter by contacting us at info@anasatech.com. We will make reasonable efforts to resolve disputes informally within 30 days.
              </p>
            </section>

            {/* Section 16 */}
            <section id="contact" className="mb-14 scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-medium text-black mb-4">16. Contact</h2>
              <p className="text-[15px] text-neutral-700 leading-relaxed mb-4">
                Questions about these Terms? Reach out:
              </p>
              <div className="bg-neutral-50 rounded-lg p-5 border border-neutral-100">
                <p className="text-base font-medium text-black">Kintari Technologies Limited</p>
                <p className="text-sm text-neutral-500 mt-0.5">Trading as Anasatech</p>
                <div className="mt-3 space-y-1">
                  <p className="text-[15px] text-neutral-700">📧 info@anasatech.com</p>
                  <p className="text-[15px] text-neutral-700">📍 Accra, Ghana</p>
                </div>
              </div>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
}
